### PR TITLE
Big testsuite cleanup: non-core features

### PR DESCRIPTION
**Pull request by Bischoff**
Backported from head

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@Bischoff despite you did not have conflicts before, it seems that there are after #447 was merged.

Have a look and let me know when I can make a final review.

**Comment by juliogonzalez** [comment]
LGTM. Waiting for conflict resolution.

**Comment by Bischoff** [comment]
Testsuite only has 2 unrelated reds when run. On my side, ok to merge apart from conflict resolution.

**Comment by juliogonzalez** [comment]
LGTM

**Pull request merged**
