### PR TITLE
Update VHM tests for the new page implementation

### PR DESCRIPTION
**Pull request by cbbayburt**
This PR updates Virtual Host Manager tests to comply with the changes implemented in [Manager-3.1: Kubernetes integration #1848](https://github.com/SUSE/spacewalk/pull/1848)

### CODE REVIEW

**Comment by cbbayburt** [comment]
On the delete scenario, there are two buttons with the same name. The correct one has class `btn-danger` so we should additionally use a class selector.

delete-btn

**Comment by cbbayburt** [comment]
It looks like Capybara cannot click on pop-up dialogs anyway. We'll need to update the method in `navigation_steps.rb`

**Comment by MalloZup** [comment]
https://github.com/SUSE/spacewalk-testsuite-base/blob/4ba13c0c690a1e1d55d6f92b319fe790622d9ea0/features/srv_docker_advanced_test.feature#L13

**Comment by cbbayburt** [comment]
@MalloZup i've tried with both `btn-danger` and `.btn-danger` but no luck
```
Unable to find button "btn-danger" (Capybara::ElementNotFound)
```

**Comment by cbbayburt** [comment]
Ah, it should be an id, not a class

**Comment by MalloZup** [comment]
@cbbayburt ```find("#btn-danger", visible: false).click```

**Comment by cbbayburt** [comment]
But I need to update the DeleteDialog component first.

**Comment by cbbayburt** [comment]
Merged and cherry-picked into `master`

**Pull request merged**
