### PR TITLE
Big testsuite cleanup: non-core features

### PR DESCRIPTION
**Pull request by Bischoff**
Second and last phase of big testsuite cleanup: applied conventions, fixed English.

### CODE REVIEW

**Comment by MalloZup** [comment]
@Bischoff  for the travis red:
you have a duplicata scenario, and for rubocop since the gem (rubocop) got updated on the travis debian container, we have from time to time new failures.

This we need to fix them, but if this are out of scope of the PR, i would suggest you to run

``` console
cd spacewalk-testsuite-base
gem update rubocop
rubocop --auto-gen-config
git diff
```
So we can blacklist the new failures and fix them later. Of course this is only because the updated gem, we blacklist them :)

**Comment by Bischoff** [comment]
Blacklisted travis problems as you suggested.

**Comment by MalloZup** [comment]
thx

**Comment by Bischoff** [comment]
thanks for the review and the merge

**Pull request merged**
