### PR TITLE
[WIP] Test suite cleanup, correcting capitalisations - manager31

### PR DESCRIPTION
**Pull request by 0rnela**

### CODE REVIEW

**Comment by MalloZup** [comment]
Would be great to have html attached. Since this can have typo thar a reviewer can not sew

**Comment by Bischoff** [comment]
Ornela is currently running the testsuite to check nothing broke

**Comment by MalloZup** [comment]
Ok if it run without pb. Thx

**Comment by Bischoff** [comment]
Yeah, sorry, we should have put WIP first - and keep it as long the tests are not finished

**Comment by Bischoff** [comment]
Tests passed, I'll merge.

**Pull request merged**
